### ISSUE TITLE
Support converting of Polyline to GeoJSON

### ISSUE THREAD

**Issue by jtheuer** [barberboy/geojson-polyline#1]
Hey,

Maybe I missed something in the documentation, but is it possible to convert from Google Polyline Encoding to Geojson?

```
> echo "yvd|Fh~gqNfEqKzBEkEvKwB?" | geojson-polyline fromPolyline
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Invalid JSON (Unexpected "y" at position 0 in state STOP)
    at Parser.proto.charError (/usr/local/lib/node_modules/geojson-polyline/node_modules/jsonparse/jsonparse.js:90:16)
    at Parser.proto.write (/usr/local/lib/node_modules/geojson-polyline/node_modules/jsonparse/jsonparse.js:154:23)
```

Thanks!

**Comment by barberboy** [comment]
Hey, sorry for the very late reply!

This library assumes that the input is [GeoJSON text](https://tools.ietf.org/html/rfc7946#section-2) with polyline-encoded coordinates, like 
```json
{"type":"Polygon","coordinates":["yvd|Fh~gqNfEqKzBEkEvKwB?J?K?"]}
```

If all you have is an encode polyline, you can use [@mapbox/polyline](https://www.npmjs.com/package/@mapbox/polyline#command-line) directly, like
```sh
$ echo "yvd|Fh~gqNfEqKzBEkEvKwB?" | polyline --decode
```

**Comment by jtheuer** [comment]
Thanks for the explanation. This was not obvious for me, I recommend you add this to the help or documentation!
