### ISSUE TITLE
Uncaught TypeError: GeoJSONPolyline[method] is not a function

### ISSUE THREAD

**Issue by esron** [barberboy/geojson-polyline#4]
I'm using the library in a Vue.js project and in every action this function gets called.
Here is my code:

```JavaScript
imgSrc() {
			if (!this.shape || !this.shape.features) return '/imgs/placeholder.jpg';

			const { coordinates: enc } = encode(this.shape.features[0].geometry);

			const width = 320;
			const height = 240;
			const fillColor = '0xFF000050';
			const color = '0xFF000080';
			const weight = 2;

			const url = `https://maps.googleapis.com/maps/api/staticmap?size=${width}x${height}&maptype=satellite&path=fillcolor:${fillColor}|color:${color}|weight:${weight}|enc:${enc}&key=MyAPIkey`;

			return encodeURI(url);
		},
```

My project is a SPA, therefore, I think the function gets called in every render of my components. 

I'll open a merge request with the solution I came up with.

**Comment by barberboy** [comment]
@esron geojson-polyline@1.0.1 has been published and is available. When you are able, could you confirm that it solves the issue you were experiencing with Vue.js?

**Comment by esron** [comment]
The problem is solved. Thank you.
