### ISSUE TITLE
Wrap LineString into proper GeoJSON

### ISSUE THREAD

**Issue by baerbock** [barberboy/geojson-polyline#6]
When I produce a LineString with your library, it's not a full GeoJSON

`{fo_FvwwlQxQ|SbExEbBpJhCzc@`FtRbSbZpAbBvAjCC`Eu@tEmB~CoWnKwl@bVq\\~N`
becomes

```
{ type: 'LineString',
  coordinates: 
   [ [ -96.6286, 36.78334 ],
     [ -96.63195, 36.78033 ],
...
     [ -96.65802, 36.78504 ],
     [ -96.66058, 36.78977 ] ] }
```

Why is there no wrapper to produce a valid GeoJSON?
```
{
  "type": "Feature",
  "geometry": {
    "type": "LineString",
    "coordinates": 
   [ [ -96.6286, 36.78334 ],
     [ -96.63195, 36.78033 ],
...
     [ -96.65802, 36.78504 ],
     [ -96.66058, 36.78977 ] ]
  },
  "properties": {}
}
```
I'm just curious, since every polyline js library I've tried out only outputs a GeoJSON fragment.

**Comment by barberboy** [comment]
So, this library takes any valid [GeoJSON object](https://tools.ietf.org/html/rfc7946#section-3), and returns that same object with just the **coordinates** encoded as polylines. The rest of the GeoJSON object is untouched. 

Since a LineString *is* full, valid GeoJSON (see https://tools.ietf.org/html/rfc7946#appendix-A.2), a LineString _in_ would result in a LineString _out_.

If you want a Feature back when you decode, you will need to encode a Feature. If you encode an entire FeatureCollection using this library, you will get back a FeatureCollection where the coordinates are encoded for every Feature.

**Comment by barberboy** [comment]
Some examples:

### Encoding a LineString
```sh
geojson-polyline encode <<EOF
{
  "type": "LineString",
  "coordinates":  [
    [ -96.6286, 36.78334 ],
    [ -96.63195, 36.78033 ],
    [ -96.65802, 36.78504 ],
    [ -96.66058, 36.78977 ]
  ] 
}
EOF
```

Result:
```json
{"type":"LineString","coordinates":"{fo_FvwwlQxQ|Sm\\|aDq\\~N"}
```

### Decoding the LineString
```sh
geojson-polyline decode '{"type":"LineString","coordinates":"{fo_FvwwlQxQ|Sm\\|aDq\\~N"}'
```
Result:
```json
{"type":"LineString","coordinates":[[-96.6286,36.78334],[-96.63195,36.78033],[-96.65802,36.78504],[-96.66058,36.78977]]}
```

### Encoding a Feature
```sh
geojson-polyline encode <<EOF
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates":  [
      [ -96.6286, 36.78334 ],
      [ -96.63195, 36.78033 ],
      [ -96.65802, 36.78504 ],
      [ -96.66058, 36.78977 ]
    ] 
  }
}
```

Result:
```json
{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":"{fo_FvwwlQxQ|Sm\\|aDq\\~N"}}
```

### Decoding the Feature
```sh
geojson-polyline decode '{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":"{fo_FvwwlQxQ|Sm\\|aDq\\~N"}}'
```

Result:
```json
{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-96.6286,36.78334],[-96.63195,36.78033],[-96.65802,36.78504],[-96.66058,36.78977]]}}
```

It should be noted that you can encode/decode entire `FeatureCollection`s, like:

```sh
geojson-polyline encode -f routes.geojson > routes-encoded.geojson
```

**Comment by barberboy** [comment]
@baerbock Does this make sense? Did you have any more questions about this library?
